### ISSUE TITLE
Occasional NPE when scrolling in debug window

### ISSUE THREAD

**Issue by nwaldispuehl** [nwaldispuehl/interval-music-compositor#30]
When scrolling in the debug window of the Apple OSX version of the software, then sometimes the following NPE occurrs.
It might be if the scrolling happens at the same time as something gets pushed to the debug log.

```
2017-10-04--20:31:19.085 - unknown - NullPointerException
2017-10-04--20:31:19.096 - IntervalMusicCompositorUI - java.lang.NullPointerException
	at javafx.scene.Scene$ScenePeerListener.scrollEvent(Scene.java:2556)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$null$369(GlassViewEventHandler.java:914)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleScrollGestureEvent$370(GlassViewEventHandler.java:896)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleScrollGestureEvent(GlassViewEventHandler.java:895)
	at com.sun.glass.ui.View.handleScrollGestureEvent(View.java:597)
	at com.sun.glass.ui.View.notifyScrollGestureEvent(View.java:1064)
	at com.sun.glass.ui.GestureSupport.handleScrollingEnd(GestureSupport.java:140)
	at com.sun.glass.ui.GestureSupport.lambda$createTouchCountListener$41(GestureSupport.java:379)
	at com.sun.glass.ui.TouchInputSupport.notifyEndTouchEvent(TouchInputSupport.java:115)
	at com.sun.glass.ui.mac.MacTouchInputSupport.notifyEndTouchEvent(MacTouchInputSupport.java:93)
	at com.sun.glass.ui.mac.MacGestureSupport.notifyEndTouchEvent(MacGestureSupport.java:81)
```

**Comment by nwaldispuehl** [comment]
Got similar exceptions when dropping tracks into the track list. Appear to be platform issues.

**Comment by nwaldispuehl** [comment]
No more sightings, this is stale.
