### ISSUE TITLE
Unexpected OutOfMemoryException when persisting compilation with FileOutputStream

### ISSUE THREAD

**Issue by nwaldispuehl** [nwaldispuehl/interval-music-compositor#32]
A user reported an interesting crash when generating a compilation.
_(Note: User identifying parts replaced with '********')_
```
2017-10-06--21:45:16.030 - IntervalMusicCompositor - Interval Music Compositor, V 2.8.0
2017-10-06--21:45:16.030 - IntervalMusicCompositor - System properties: os: Windows 10, os arch: x86, jvm: 1.8.0_144, jvm arch: 32, max heap size: 989 MB
2017-10-06--21:45:16.030 - UiUserPreferences - Loading user preference 'locale' value: de
...
2017-10-06--21:46:09.159 - MainControl - Started compilation with: [60] [120] 8
2017-10-06--21:46:09.161 - CompilationGenerator - Progress: 0, Lese Daten ein
2017-10-06--21:46:09.161 - CompilationGenerator - Progress: 10, Lade Musikdateien
2017-10-06--21:46:09.161 - CompilationGenerator - Progress: 20, Lade Pausenmusikdateien
2017-10-06--21:46:09.162 - CompilationGenerator - Progress: 30, Erzeuge Wiedergabeliste
2017-10-06--21:46:09.171 - CompilationGenerator - Progress: 40, Erzeuge Zusammenstellung
2017-10-06--21:46:09.237 - Compilation - Generate compilation of length: 1440 s
2017-10-06--21:46:09.346 - Compilation - Adding to compilation at 0.0: Various - Beach Boys  Sloop John B..mp3 [87547 - 147547]
2017-10-06--21:46:09.426 - Compilation - Adding to compilation at 60.0: Break [0 - 120000]
2017-10-06--21:46:09.510 - Compilation - Adding to compilation at 180.0: Various - Byrds  Mr. Tambourine Man.mp3 [8766 - 68766]
2017-10-06--21:46:09.565 - Compilation - Adding to compilation at 240.0: Break [0 - 120000]
2017-10-06--21:46:09.648 - Compilation - Adding to compilation at 360.0: Various - Tommy Roe  Sheila.mp3 [10042 - 70042]
2017-10-06--21:46:09.687 - Compilation - Adding to compilation at 420.0: Break [0 - 120000]
2017-10-06--21:46:09.774 - Compilation - Adding to compilation at 540.0: Various - Archies  Sugar, Sugar.mp3 [63475 - 123475]
2017-10-06--21:46:09.815 - Compilation - Adding to compilation at 600.0: Break [0 - 120000]
2017-10-06--21:46:09.900 - Compilation - Adding to compilation at 720.0: Various - Hollies  Jennifer Eccles.mp3 [75568 - 135568]
2017-10-06--21:46:09.940 - Compilation - Adding to compilation at 780.0: Break [0 - 120000]
2017-10-06--21:46:10.023 - Compilation - Adding to compilation at 900.0: Various - Small Faces  Shalalalalee.mp3 [55592 - 115592]
2017-10-06--21:46:10.063 - Compilation - Adding to compilation at 960.0: Break [0 - 120000]
2017-10-06--21:46:10.150 - Compilation - Adding to compilation at 1080.0: Various - Los Bravos  Black Is Black.mp3 [76246 - 136246]
2017-10-06--21:46:10.191 - Compilation - Adding to compilation at 1140.0: Break [0 - 120000]
2017-10-06--21:46:10.273 - Compilation - Adding to compilation at 1260.0: Various - Box Tops  The Letter.mp3 [16394 - 76394]
2017-10-06--21:46:10.313 - Compilation - Adding to compilation at 1320.0: Break [0 - 120000]
2017-10-06--21:46:10.314 - Compilation - Adding sound effect gong at 0
2017-10-06--21:46:10.318 - Compilation - Adding sound effect gong at 180000
2017-10-06--21:46:10.323 - Compilation - Adding sound effect gong at 360000
2017-10-06--21:46:10.327 - Compilation - Adding sound effect gong at 540000
2017-10-06--21:46:10.331 - Compilation - Adding sound effect gong at 720000
2017-10-06--21:46:10.335 - Compilation - Adding sound effect gong at 900000
2017-10-06--21:46:10.339 - Compilation - Adding sound effect gong at 1080000
2017-10-06--21:46:10.342 - Compilation - Adding sound effect gong at 1260000
2017-10-06--21:46:10.347 - CompilationGenerator - Created temporary compilation file C:\Users\********\AppData\Local\Temp\compilation4154158354489334135.imc_wav for size 254016000
2017-10-06--21:46:10.347 - unknown - Das Programm benötigt für einen Vorgang mehr Hauptspeicher (RAM) als es zugewiesen erhielt.
null
2017-10-06--21:46:10.349 - IntervalMusicCompositorUI - ch.retorte.intervalmusiccompositor.compilation.CompilationException: Das Programm benötigt für einen Vorgang mehr Hauptspeicher (RAM) als es zugewiesen erhielt.
null
	at ch.retorte.intervalmusiccompositor.compilation.CompilationGenerator.createCompilation(CompilationGenerator.java:257)
	at ch.retorte.intervalmusiccompositor.compilation.CompilationGenerator.run(CompilationGenerator.java:102)
	at java.lang.Thread.run(Unknown Source)
...
```

The interesting part is that at this position in the code:
```
try (FileOutputStream fos = new FileOutputStream(compilationDataFile)) {
      fos.write(compilationBytes);
}
```
it is not immediately clear how such `OutOfMemoryException` could be produced.

**Comment by nwaldispuehl** [comment]
Was not able to reproduce it.
