### ISSUE TITLE
'Double whistle' special effect can be placed out of range

### ISSUE THREAD

**Issue by nwaldispuehl** [nwaldispuehl/interval-music-compositor#48]
The maximum start time of a special effect is defined as:
```
maximum_special_effect_start_time := sound_period_duration - sound_effect_duration
```
However -- in the case of the 'double whistle' -- this appears to be not the case; it can be placed at the end of a sound interval. E.g. if the sound interval is `8 s`, then the maximum time is not `7 s` but actually `8 s`. Which causes an Exception:
```
2018-07-19--19:18:19.422 - Compilation - Adding sound effect double_whistle (1000) at 8000 ms
There was a problem!
If inserted at position 1411200, the inserted array of length 176360 exceeds the length of the host array: 1411200
2018-07-19--19:18:19.428 - IntervalMusicCompositorUI - ch.retorte.intervalmusiccompositor.compilation.CompilationException: There was a problem!
If inserted at position 1411200, the inserted array of length 176360 exceeds the length of the host array: 1411200
	at ch.retorte.intervalmusiccompositor.compilation.CompilationGenerator.createCompilation(CompilationGenerator.java:272)
	at ch.retorte.intervalmusiccompositor.compilation.CompilationGenerator.run(CompilationGenerator.java:102)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: If inserted at position 1411200, the inserted array of length 176360 exceeds the length of the host array: 1411200
	at ch.retorte.intervalmusiccompositor.commons.ArrayHelper.insertAt(ArrayHelper.java:62)
	at ch.retorte.intervalmusiccompositor.compilation.Compilation.addSoundEffectTo(Compilation.java:244)
	at ch.retorte.intervalmusiccompositor.compilation.Compilation.getPlaylistItemDataFrom(Compilation.java:162)
	at ch.retorte.intervalmusiccompositor.compilation.Compilation.generateCompilation(Compilation.java:82)
	at ch.retorte.intervalmusiccompositor.compilation.CompilationGenerator.createCompilation(CompilationGenerator.java:248)
	... 2 more
```

**Comment by nwaldispuehl** [comment]
Ah, the 'double whistle' has an actual duration of `999 ms` which was oddly rounded in some integer operation.
