### ISSUE TITLE
Self-Upgrade: Downloading new version fails with 'handshake failure'

### ISSUE THREAD

**Issue by nwaldispuehl** [nwaldispuehl/interval-music-compositor#64]
When trying to download the latest version `2.11.1` from `2.11.0` with the new, experimental "Upgrade and restart (beta)" button, it fails when trying to download the latest version archive from the github servers with this exception:

```
2021-11-13--14:21:03.463 - ModuleReplacingVersionUpgrader - Successfully created empty file.
2021-11-13--14:21:03.463 - ModuleReplacingVersionUpgrader - Starting download.
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:357)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:203)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at java.base/java.net.URL.openStream(URL.java:1161)
	at intervalmusiccompositor.core/ch.retorte.intervalmusiccompositor.util.ModuleReplacingVersionUpgrader.downloadToUpgradeDir(ModuleReplacingVersionUpgrader.java:202)
	at intervalmusiccompositor.core/ch.retorte.intervalmusiccompositor.util.ModuleReplacingVersionUpgrader.upgradeTo(ModuleReplacingVersionUpgrader.java:79)
	at intervalmusiccompositor.ui.fx/ch.retorte.intervalmusiccompositor.ui.updatecheck.UpdateCheckDialog$1.call(UpdateCheckDialog.java:174)
	at intervalmusiccompositor.ui.fx/ch.retorte.intervalmusiccompositor.ui.updatecheck.UpdateCheckDialog$1.call(UpdateCheckDialog.java:169)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
2021-11-13--14:21:03.521 - ModuleReplacingVersionUpgrader - Received fatal alert: handshake_failure
```

**Comment by nwaldispuehl** [comment]
The complete debug sequence with the `-Djavax.net.debug=all` flag set here:

```
2021-11-13--14:31:18.249 - ModuleReplacingVersionUpgrader - Starting download.
javax.net.ssl|DEBUG|15|Thread-46|2021-11-13 14:31:18.284 CET|Utilities.java:74|the previous server name in SNI (type=host_name (0), value=github.com) was replaced with (type=host_name (0), value=github.com)
javax.net.ssl|DEBUG|15|Thread-46|2021-11-13 14:31:18.284 CET|HandshakeContext.java:298|Ignore unsupported cipher suite: TLS_AES_256_GCM_SHA384 for TLSv1.2
javax.net.ssl|DEBUG|15|Thread-46|2021-11-13 14:31:18.284 CET|HandshakeContext.java:298|Ignore unsupported cipher suite: TLS_AES_128_GCM_SHA256 for TLSv1.2
javax.net.ssl|DEBUG|15|Thread-46|2021-11-13 14:31:18.284 CET|HandshakeContext.java:298|Ignore unsupported cipher suite: TLS_CHACHA20_POLY1305_SHA256 for TLSv1.2
javax.net.ssl|INFO|15|Thread-46|2021-11-13 14:31:18.285 CET|AlpnExtension.java:182|No available application protocols
javax.net.ssl|DEBUG|15|Thread-46|2021-11-13 14:31:18.285 CET|SSLExtensions.java:272|Ignore, context unavailable extension: application_layer_protocol_negotiation
javax.net.ssl|DEBUG|15|Thread-46|2021-11-13 14:31:18.285 CET|SessionTicketExtension.java:408|Stateless resumption supported
javax.net.ssl|ALL|15|Thread-46|2021-11-13 14:31:18.285 CET|SignatureScheme.java:393|Ignore unsupported signature scheme: ecdsa_secp256r1_sha256
javax.net.ssl|ALL|15|Thread-46|2021-11-13 14:31:18.285 CET|SignatureScheme.java:393|Ignore unsupported signature scheme: ecdsa_secp384r1_sha384
javax.net.ssl|ALL|15|Thread-46|2021-11-13 14:31:18.285 CET|SignatureScheme.java:393|Ignore unsupported signature scheme: ecdsa_secp521r1_sha512
javax.net.ssl|ALL|15|Thread-46|2021-11-13 14:31:18.285 CET|SignatureScheme.java:393|Ignore unsupported signature scheme: ed25519
javax.net.ssl|ALL|15|Thread-46|2021-11-13 14:31:18.285 CET|SignatureScheme.java:393|Ignore unsupported signature scheme: ed448
javax.net.ssl|ALL|15|Thread-46|2021-11-13 14:31:18.285 CET|SignatureScheme.java:393|Ignore unsupported signature scheme: ecdsa_sha224
javax.net.ssl|ALL|15|Thread-46|2021-11-13 14:31:18.286 CET|SignatureScheme.java:393|Ignore unsupported signature scheme: ecdsa_sha1
javax.net.ssl|ALL|15|Thread-46|2021-11-13 14:31:18.286 CET|SignatureScheme.java:412|Ignore disabled signature scheme: rsa_md5
javax.net.ssl|DEBUG|15|Thread-46|2021-11-13 14:31:18.286 CET|SSLExtensions.java:272|Ignore, context unavailable extension: cookie
javax.net.ssl|DEBUG|15|Thread-46|2021-11-13 14:31:18.295 CET|SSLExtensions.java:272|Ignore, context unavailable extension: renegotiation_info
javax.net.ssl|DEBUG|15|Thread-46|2021-11-13 14:31:18.295 CET|PreSharedKeyExtension.java:661|No session to resume.
javax.net.ssl|DEBUG|15|Thread-46|2021-11-13 14:31:18.295 CET|SSLExtensions.java:272|Ignore, context unavailable extension: pre_shared_key
javax.net.ssl|DEBUG|15|Thread-46|2021-11-13 14:31:18.297 CET|ClientHello.java:641|Produced ClientHello handshake message (
"ClientHello": {
  "client version"      : "TLSv1.2",
  "random"              : "D23A8CB901373FE6542500145D23D8CCE5C5120149D41285292DC98F7CD99242",
  "session id"          : "BED1CF8ED6F5164B61D011F657C0E8A1BF63AD9DD783B0FBF251C2E941C3AA4A",
  "cipher suites"       : "[TLS_AES_256_GCM_SHA384(0x1302), TLS_AES_128_GCM_SHA256(0x1301), TLS_CHACHA20_POLY1305_SHA256(0x1303), TLS_DHE_RSA_WITH_AES_256_GCM_SHA384(0x009F), TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256(0xCCAA), TLS_DHE_DSS_WITH_AES_256_GCM_SHA384(0x00A3), TLS_DHE_RSA_WITH_AES_128_GCM_SHA256(0x009E), TLS_DHE_DSS_WITH_AES_128_GCM_SHA256(0x00A2), TLS_DHE_RSA_WITH_AES_256_CBC_SHA256(0x006B), TLS_DHE_DSS_WITH_AES_256_CBC_SHA256(0x006A), TLS_DHE_RSA_WITH_AES_128_CBC_SHA256(0x0067), TLS_DHE_DSS_WITH_AES_128_CBC_SHA256(0x0040), TLS_DHE_RSA_WITH_AES_256_CBC_SHA(0x0039), TLS_DHE_DSS_WITH_AES_256_CBC_SHA(0x0038), TLS_DHE_RSA_WITH_AES_128_CBC_SHA(0x0033), TLS_DHE_DSS_WITH_AES_128_CBC_SHA(0x0032), TLS_RSA_WITH_AES_256_GCM_SHA384(0x009D), TLS_RSA_WITH_AES_128_GCM_SHA256(0x009C), TLS_RSA_WITH_AES_256_CBC_SHA256(0x003D), TLS_RSA_WITH_AES_128_CBC_SHA256(0x003C), TLS_RSA_WITH_AES_256_CBC_SHA(0x0035), TLS_RSA_WITH_AES_128_CBC_SHA(0x002F), TLS_EMPTY_RENEGOTIATION_INFO_SCSV(0x00FF)]",
  "compression methods" : "00",
  "extensions"          : [
    "server_name (0)": {
      type=host_name (0), value=github.com
    },
    "status_request (5)": {
      "certificate status type": ocsp
      "OCSP status request": {
        "responder_id": <empty>
        "request extensions": {
          <empty>
        }
      }
    },
    "supported_groups (10)": {
      "versions": [ffdhe2048, ffdhe3072, ffdhe4096, ffdhe6144, ffdhe8192]
    },
    "ec_point_formats (11)": {
      "formats": [uncompressed]
    },
    "status_request_v2 (17)": {
      "cert status request": {
        "certificate status type": ocsp_multi
        "OCSP status request": {
          "responder_id": <empty>
          "request extensions": {
            <empty>
          }
        }
      }
    },
    "extended_master_secret (23)": {
      <empty>
    },
    "session_ticket (35)": {
      <empty>
    },
    "signature_algorithms (13)": {
      "signature schemes": [rsa_pss_rsae_sha256, rsa_pss_rsae_sha384, rsa_pss_rsae_sha512, rsa_pss_pss_sha256, rsa_pss_pss_sha384, rsa_pss_pss_sha512, rsa_pkcs1_sha256, rsa_pkcs1_sha384, rsa_pkcs1_sha512, dsa_sha256, rsa_sha224, dsa_sha224, rsa_pkcs1_sha1, dsa_sha1]
    },
    "supported_versions (43)": {
      "versions": [TLSv1.3, TLSv1.2]
    },
    "psk_key_exchange_modes (45)": {
      "ke_modes": [psk_dhe_ke]
    },
    "signature_algorithms_cert (50)": {
      "signature schemes": [rsa_pss_rsae_sha256, rsa_pss_rsae_sha384, rsa_pss_rsae_sha512, rsa_pss_pss_sha256, rsa_pss_pss_sha384, rsa_pss_pss_sha512, rsa_pkcs1_sha256, rsa_pkcs1_sha384, rsa_pkcs1_sha512, dsa_sha256, rsa_sha224, dsa_sha224, rsa_pkcs1_sha1, dsa_sha1]
    },
    "key_share (51)": {
      "client_shares": [  
        {
          "named group": ffdhe2048
          "key_exchange": {
            0000: 97 36 5D 42 C3 A5 E9 B3   C6 F7 F2 11 AF D7 CF CF  .6]B............
            0010: E7 A3 F8 B2 FB 8C 30 52   EC 0D 81 10 DE C0 CE E2  ......0R........
            0020: 3D 40 1B 11 51 41 2E 25   B1 45 B0 FB C5 CC B1 0E  =@..QA.%.E......
            0030: B8 05 61 B6 1A 3B BE 85   2D D5 6A 20 A1 8D 02 1C  ..a..;..-.j ....
            0040: AA 5D 6B 50 DA DF 87 41   A9 72 2E E4 10 81 32 86  .]kP...A.r....2.
            0050: 1A 3B 7F 99 4B F1 84 3F   80 54 84 25 7D 0A 14 3C  .;..K..?.T.%...<
            0060: 19 BB A9 2C E2 7E B4 B6   84 79 93 E3 CB CB 47 71  ...,.....y....Gq
            0070: BA E3 19 A5 25 D4 C7 FC   9F C1 9F 6E 8E 57 44 5D  ....%......n.WD]
            0080: 62 70 44 EA E4 6A 8C CC   E0 D1 A7 EB 58 8E E1 AC  bpD..j......X...
            0090: EE 1C 7E BA 80 17 83 8E   F8 CB DB C8 7B 34 C3 3A  .............4.:
            00A0: 7A B1 40 5B 97 1A 0E DE   49 37 CD 6D F9 1B F4 A1  z.@[....I7.m....
            00B0: C6 FE 08 A3 DD 6A 73 85   E8 6F 25 BF F0 C2 0C 79  .....js..o%....y
            00C0: B8 80 77 E2 D9 AC 60 92   E8 26 92 32 47 55 37 0B  ..w...`..&.2GU7.
            00D0: 11 53 BF 87 6B 56 18 75   C7 C8 C9 EC E1 3A 33 54  .S..kV.u.....:3T
            00E0: 5F C9 C9 36 C1 14 B5 FD   48 84 16 FD BD 6F 8C D1  _..6....H....o..
            00F0: 63 AD 60 14 60 B0 1E A3   0D C2 04 E6 80 76 7B 67  c.`.`........v.g
          }
        },
      ]
    }
  ]
}
)
javax.net.ssl|DEBUG|15|Thread-46|2021-11-13 14:31:18.297 CET|SSLSocketOutputRecord.java:256|WRITE: TLSv1.3 handshake, length = 543
javax.net.ssl|DEBUG|15|Thread-46|2021-11-13 14:31:18.298 CET|SSLSocketOutputRecord.java:270|Raw write (
  0000: 16 03 03 02 1F 01 00 02   1B 03 03 D2 3A 8C B9 01  ............:...
  0010: 37 3F E6 54 25 00 14 5D   23 D8 CC E5 C5 12 01 49  7?.T%..]#......I
  0020: D4 12 85 29 2D C9 8F 7C   D9 92 42 20 BE D1 CF 8E  ...)-.....B ....
  0030: D6 F5 16 4B 61 D0 11 F6   57 C0 E8 A1 BF 63 AD 9D  ...Ka...W....c..
  0040: D7 83 B0 FB F2 51 C2 E9   41 C3 AA 4A 00 2E 13 02  .....Q..A..J....
  0050: 13 01 13 03 00 9F CC AA   00 A3 00 9E 00 A2 00 6B  ...............k
  0060: 00 6A 00 67 00 40 00 39   00 38 00 33 00 32 00 9D  .j.g.@.9.8.3.2..
  0070: 00 9C 00 3D 00 3C 00 35   00 2F 00 FF 01 00 01 A4  ...=.<.5./......
  0080: 00 00 00 0F 00 0D 00 00   0A 67 69 74 68 75 62 2E  .........github.
  0090: 63 6F 6D 00 05 00 05 01   00 00 00 00 00 0A 00 0C  com.............
  00A0: 00 0A 01 00 01 01 01 02   01 03 01 04 00 0B 00 02  ................
  00B0: 01 00 00 11 00 09 00 07   02 00 04 00 00 00 00 00  ................
  00C0: 17 00 00 00 23 00 00 00   0D 00 1E 00 1C 08 04 08  ....#...........
  00D0: 05 08 06 08 09 08 0A 08   0B 04 01 05 01 06 01 04  ................
  00E0: 02 03 01 03 02 02 01 02   02 00 2B 00 05 04 03 04  ..........+.....
  00F0: 03 03 00 2D 00 02 01 01   00 32 00 1E 00 1C 08 04  ...-.....2......
  0100: 08 05 08 06 08 09 08 0A   08 0B 04 01 05 01 06 01  ................
  0110: 04 02 03 01 03 02 02 01   02 02 00 33 01 06 01 04  ...........3....
  0120: 01 00 01 00 97 36 5D 42   C3 A5 E9 B3 C6 F7 F2 11  .....6]B........
  0130: AF D7 CF CF E7 A3 F8 B2   FB 8C 30 52 EC 0D 81 10  ..........0R....
  0140: DE C0 CE E2 3D 40 1B 11   51 41 2E 25 B1 45 B0 FB  ....=@..QA.%.E..
  0150: C5 CC B1 0E B8 05 61 B6   1A 3B BE 85 2D D5 6A 20  ......a..;..-.j 
  0160: A1 8D 02 1C AA 5D 6B 50   DA DF 87 41 A9 72 2E E4  .....]kP...A.r..
  0170: 10 81 32 86 1A 3B 7F 99   4B F1 84 3F 80 54 84 25  ..2..;..K..?.T.%
  0180: 7D 0A 14 3C 19 BB A9 2C   E2 7E B4 B6 84 79 93 E3  ...<...,.....y..
  0190: CB CB 47 71 BA E3 19 A5   25 D4 C7 FC 9F C1 9F 6E  ..Gq....%......n
  01A0: 8E 57 44 5D 62 70 44 EA   E4 6A 8C CC E0 D1 A7 EB  .WD]bpD..j......
  01B0: 58 8E E1 AC EE 1C 7E BA   80 17 83 8E F8 CB DB C8  X...............
  01C0: 7B 34 C3 3A 7A B1 40 5B   97 1A 0E DE 49 37 CD 6D  .4.:z.@[....I7.m
  01D0: F9 1B F4 A1 C6 FE 08 A3   DD 6A 73 85 E8 6F 25 BF  .........js..o%.
  01E0: F0 C2 0C 79 B8 80 77 E2   D9 AC 60 92 E8 26 92 32  ...y..w...`..&.2
  01F0: 47 55 37 0B 11 53 BF 87   6B 56 18 75 C7 C8 C9 EC  GU7..S..kV.u....
  0200: E1 3A 33 54 5F C9 C9 36   C1 14 B5 FD 48 84 16 FD  .:3T_..6....H...
  0210: BD 6F 8C D1 63 AD 60 14   60 B0 1E A3 0D C2 04 E6  .o..c.`.`.......
  0220: 80 76 7B 67                                        .v.g
)
javax.net.ssl|DEBUG|15|Thread-46|2021-11-13 14:31:18.312 CET|SSLSocketInputRecord.java:488|Raw read (
  0000: 15 03 03 00 02                                     .....
)
javax.net.ssl|DEBUG|15|Thread-46|2021-11-13 14:31:18.313 CET|SSLSocketInputRecord.java:214|READ: TLSv1.2 alert, length = 2
javax.net.ssl|DEBUG|15|Thread-46|2021-11-13 14:31:18.313 CET|SSLSocketInputRecord.java:488|Raw read (
  0000: 02 28                                              .(
)
javax.net.ssl|DEBUG|15|Thread-46|2021-11-13 14:31:18.313 CET|SSLSocketInputRecord.java:247|READ: TLSv1.2 alert, length = 2
javax.net.ssl|DEBUG|15|Thread-46|2021-11-13 14:31:18.313 CET|Alert.java:238|Received alert message (
"Alert": {
  "level"      : "fatal",
  "description": "handshake_failure"
}
)
javax.net.ssl|ERROR|15|Thread-46|2021-11-13 14:31:18.313 CET|TransportContext.java:362|Fatal (HANDSHAKE_FAILURE): Received fatal alert: handshake_failure (
"throwable" : {
  javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
  	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
  	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:357)
  	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
  	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:203)
  	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
  	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
  	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
  	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
  	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
  	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
  	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
  	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
  	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
  	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
  	at java.base/java.net.URL.openStream(URL.java:1161)
  	at intervalmusiccompositor.core/ch.retorte.intervalmusiccompositor.util.ModuleReplacingVersionUpgrader.downloadToUpgradeDir(ModuleReplacingVersionUpgrader.java:202)
  	at intervalmusiccompositor.core/ch.retorte.intervalmusiccompositor.util.ModuleReplacingVersionUpgrader.upgradeTo(ModuleReplacingVersionUpgrader.java:79)
  	at intervalmusiccompositor.ui.fx/ch.retorte.intervalmusiccompositor.ui.updatecheck.UpdateCheckDialog$1.call(UpdateCheckDialog.java:174)
  	at intervalmusiccompositor.ui.fx/ch.retorte.intervalmusiccompositor.ui.updatecheck.UpdateCheckDialog$1.call(UpdateCheckDialog.java:169)
  	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.lang.Thread.run(Thread.java:833)}

)
javax.net.ssl|ALL|15|Thread-46|2021-11-13 14:31:18.314 CET|SSLSessionImpl.java:1222|Invalidated session:  Session(1636810278249|SSL_NULL_WITH_NULL_NULL)
javax.net.ssl|DEBUG|15|Thread-46|2021-11-13 14:31:18.314 CET|SSLSocketImpl.java:1749|close the underlying socket
javax.net.ssl|DEBUG|15|Thread-46|2021-11-13 14:31:18.314 CET|SSLSocketImpl.java:1775|close the SSL connection (passive)
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:357)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:203)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at java.base/java.net.URL.openStream(URL.java:1161)
	at intervalmusiccompositor.core/ch.retorte.intervalmusiccompositor.util.ModuleReplacingVersionUpgrader.downloadToUpgradeDir(ModuleReplacingVersionUpgrader.java:202)
	at intervalmusiccompositor.core/ch.retorte.intervalmusiccompositor.util.ModuleReplacingVersionUpgrader.upgradeTo(ModuleReplacingVersionUpgrader.java:79)
	at intervalmusiccompositor.ui.fx/ch.retorte.intervalmusiccompositor.ui.updatecheck.UpdateCheckDialog$1.call(UpdateCheckDialog.java:174)
	at intervalmusiccompositor.ui.fx/ch.retorte.intervalmusiccompositor.ui.updatecheck.UpdateCheckDialog$1.call(UpdateCheckDialog.java:169)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
2021-11-13--14:31:18.314 - ModuleReplacingVersionUpgrader - Received fatal alert: handshake_failure
javax.net.ssl|DEBUG|F4|Keep-Alive-Timer|2021-11-13 14:31:18.947 CET|SSLSocketImpl.java:572|duplex close of SSLSocket
javax.net.ssl|DEBUG|F4|Keep-Alive-Timer|2021-11-13 14:31:18.947 CET|SSLSocketOutputRecord.java:71|WRITE: TLSv1.2 alert(close_notify), length = 10
javax.net.ssl|DEBUG|F4|Keep-Alive-Timer|2021-11-13 14:31:18.947 CET|SSLCipher.java:1773|Plaintext before ENCRYPTION (
  0000: 01 00                                              ..
)
javax.net.ssl|DEBUG|F4|Keep-Alive-Timer|2021-11-13 14:31:18.947 CET|SSLSocketOutputRecord.java:85|Raw write (
  0000: 15 03 03 00 1A 00 00 00   00 00 00 00 02 3F A6 B0  .............?..
  0010: 39 07 32 61 B8 A5 85 F1   70 DF 61 96 BE BD 2D     9.2a....p.a...-
)
javax.net.ssl|DEBUG|F4|Keep-Alive-Timer|2021-11-13 14:31:18.948 CET|SSLSocketImpl.java:1749|close the underlying socket
javax.net.ssl|DEBUG|F4|Keep-Alive-Timer|2021-11-13 14:31:18.948 CET|SSLSocketImpl.java:1775|close the SSL connection (initiative)
javax.net.ssl|DEBUG|F4|Keep-Alive-Timer|2021-11-13 14:31:18.948 CET|SSLSocketImpl.java:828|close inbound of SSLSocket
javax.net.ssl|WARNING|F4|Keep-Alive-Timer|2021-11-13 14:31:18.948 CET|SSLSocketImpl.java:590|SSLSocket duplex close failed. Debug info only. Exception details: (
"throwable" : {
  java.net.SocketException: Socket is closed
  	at java.base/java.net.Socket.shutdownInput(Socket.java:1601)
  	at java.base/sun.security.ssl.BaseSSLSocketImpl.shutdownInput(BaseSSLSocketImpl.java:217)
  	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:843)
  	at java.base/sun.security.ssl.SSLSocketImpl.bruteForceCloseInput(SSLSocketImpl.java:793)
  	at java.base/sun.security.ssl.SSLSocketImpl.duplexCloseOutput(SSLSocketImpl.java:655)
  	at java.base/sun.security.ssl.SSLSocketImpl.close(SSLSocketImpl.java:579)
  	at java.base/sun.net.www.http.HttpClient.closeServer(HttpClient.java:1104)
  	at java.base/sun.net.www.http.KeepAliveCache.run(KeepAliveCache.java:208)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  	at java.base/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)}

)

```

**Comment by nwaldispuehl** [comment]
Ah yes, the modularized, bundled Java runtime does only have the modules available which are explicitly specified by the `module-info.java` files. Some crypto-libraries in loosly coupled modules were used for this SSL connection, but they were not available at runtime.
