### ISSUE TITLE
Instant crash with message "Exception in Application start method" -- Assistive Technology not found

### ISSUE THREAD

**Issue by nwaldispuehl** [nwaldispuehl/interval-music-compositor#66]
A user running the software on this system:
```
os: Windows 10, os arch: amd64, jvm: 17.0.1, jvm arch: 64, current heap: 266.3 MB, max heap: 4.3 GB, free mem: 261.2 MB, total mem: 17.0 GB, free hdd: 110.8 GB, total hdd: 498.8 GB
```
encountered a crash on startup:
```
2022-03-28--20:50:10.270 - String - Failed to launch JavaFX application.
java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.awt.AWTError: Assistive Technology not found: com.sun.java.accessibility.AccessBridge
	at java.desktop/java.awt.Toolkit.newAWTError(Toolkit.java:479)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:495)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:544)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:605)
	at java.desktop/javax.swing.UIManager.<clinit>(UIManager.java:389)
	at java.desktop/javax.swing.filechooser.WindowsFileSystemView.<clinit>(FileSystemView.java:842)
	at java.desktop/javax.swing.filechooser.FileSystemView.getFileSystemView(FileSystemView.java:86)
	at intervalmusiccompositor.commons/ch.retorte.intervalmusiccompositor.commons.platform.WindowsPlatform.getDesktopPath(WindowsPlatform.java:33)
	at intervalmusiccompositor.ui.fx/ch.retorte.intervalmusiccompositor.ui.IntervalMusicCompositorUI.initializeCompilationParameters(IntervalMusicCompositorUI.java:192)
	at intervalmusiccompositor.ui.fx/ch.retorte.intervalmusiccompositor.ui.IntervalMusicCompositorUI.startMainProgramIn(IntervalMusicCompositorUI.java:181)
	at intervalmusiccompositor.ui.fx/ch.retorte.intervalmusiccompositor.ui.IntervalMusicCompositorUI.start(IntervalMusicCompositorUI.java:125)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	... 1 more
Caused by: java.lang.ClassNotFoundException: com.sun.java.accessibility.AccessBridge
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:492)
	... 27 more
```
Presumably due to a accessability feature being active. 

Adding the respective Java module dependency to the UI module should fix it:
```
requires jdk.accessibility
```

**Comment by nwaldispuehl** [comment]
The setting was most likely present from another Java installation as
https://docs.oracle.com/en/java/javase/17/access/accessibility-properties.html#GUID-077E391C-A12C-49A9-98BF-5F28F73872C9
says (emphasis mine):
> You can also specify properties in a file named .accessibility.properties in the user's home directory or a file named accessibility.properties in the $JAVA_HOME/conf directory. In the former case, the properties are used for the current user, and in the latter case, the properties are used for all users of that Java installation. **The properties set for the current user take precedence over the properties set for the Java installation**.

To reproduce the issue one can create a file `accessibility.properties` in the `conf/` directory of the distribution with the following content:
```
assistive_technologies=com.sun.java.accessibility.AccessBridge
screen_magnifier_present=true
```

**Comment by nwaldispuehl** [comment]
We mitigated the problem in our software by just swallowing this specific exception.
