### ISSUE TITLE
NullPointerException when opening output directory chooser

### ISSUE THREAD

**Issue by nwaldispuehl** [nwaldispuehl/interval-music-compositor#81]
A user encountered a NPE presumably when clicking on the 'Choose output directory' button:
```
2024-01-07--14:42:26.254 - UiUserPreferences - Loading user preference 'keepFieldState' value: true
2024-01-07--14:42:26.270 - UiUserPreferences - Loading user preference 'searchUpdateAtStartup' value: true
2024-01-07--14:42:26.270 - IntervalMusicCompositor - Interval Music Compositor, V 2.11.6
2024-01-07--14:42:26.316 - IntervalMusicCompositor - System properties: os: Windows 10, os arch: amd64, jvm: 21.0.1, jvm arch: 64, current heap: 266.3 MB, max heap: 4.3 GB, free mem: 260.8 MB, total mem: 17.0 GB, free hdd: 52.4 GB, total hdd: 498.8 GB
2024-01-07--14:42:26.316 - IntervalMusicCompositor - Selected locale: de
2024-01-07--14:42:26.395 - MainControl - Looking for old temporary files to delete in: C:\Users\<redacted>\AppData\Local\Temp
2024-01-07--14:42:26.597 - UiUserPreferences - Loading user preference 'lastProgramVersion' value: 2.11.6
2024-01-07--14:42:26.602 - IntervalMusicCompositorUI - Should we show the first start window? Current version: 2.11.6, version of previous start: 2.11.6, unrevised settings: false, verdict: false
2024-01-07--14:42:26.602 - UiUserPreferences - Loading user preference 'searchUpdateAtStartup' value: true
2024-01-07--14:42:26.606 - IntervalMusicCompositorUI - Should we check for a new version? User revised setting: true, search update at startup setting: true, verdict: true
2024-01-07--14:42:26.606 - IntervalMusicCompositorUI - Starting version check.
2024-01-07--14:42:26.610 - UpdateChecker - Attempting to fetch remote version on URL: https://interval-music-compositor.retorte.ch/current_version.txt
2024-01-07--14:42:26.616 - UpdateChecker - Setting user agent to: Interval Music Compositor [Update Checker] (v: 2.11.6, os: Windows 10, os arch: amd64, jvm: 21.0.1, jvm arch: 64, current heap: 266.3 MB, max heap: 4.3 GB, free mem: 254.0 MB, total mem: 17.0 GB, free hdd: 52.4 GB, total hdd: 498.8 GB, locale: de)
2024-01-07--14:42:27.092 - UpdateChecker - Fetched remote version string: 2.11.6
2024-01-07--14:42:27.632 - unknown - Swallowed an error due to accessibility technology declared in the `$USER_HOME/.accessibility.properties` file. Do you still need it? If not better delete the properties file.
2024-01-07--14:42:27.739 - MainScreenController - Changed contents of field 'outputFileFormat' from: '<empty>' to 'mp3'
2024-01-07--14:42:27.754 - UiUserPreferences - Loading user preference 'keepFieldState' value: true
2024-01-07--14:42:27.755 - MainScreenController - Loading stored compilation parameters from the last session.
2024-01-07--14:42:27.755 - UiUserPreferences - Loading user preference 'musicTrackList' value: 
2024-01-07--14:42:27.765 - MainScreenController - Retrieved music track files: []
2024-01-07--14:42:27.765 - UiUserPreferences - Loading user preference 'breakTrackList' value: 
2024-01-07--14:42:27.765 - MainScreenController - Retrieved break track files: []
2024-01-07--14:42:27.765 - UiUserPreferences - Loading user preference 'enumerationMode' value: SINGLE_EXTRACT
2024-01-07--14:42:27.765 - UiUserPreferences - Loading user preference 'soundPeriod' value: 0
2024-01-07--14:42:27.766 - UiUserPreferences - Loading user preference 'breakPeriod' value: 0
2024-01-07--14:42:27.766 - UiUserPreferences - Loading user preference 'soundPattern' value: 
2024-01-07--14:42:27.766 - UiUserPreferences - Loading user preference 'breakPattern' value: 
2024-01-07--14:42:27.766 - UiUserPreferences - Loading user preference 'breakVolume' value: 100
2024-01-07--14:42:27.766 - UiUserPreferences - Loading user preference 'periodTab' value: simpleTab
2024-01-07--14:42:27.767 - UiUserPreferences - Loading user preference 'blendMode' value: SEPARATE
2024-01-07--14:42:27.767 - UiUserPreferences - Loading user preference 'iterations' value: 0
2024-01-07--14:42:27.767 - UiUserPreferences - Loading user preference 'blendDuration' value: 1
2024-01-07--14:42:27.767 - UiUserPreferences - Loading user preference 'outputFileFormat' value: mp3
2024-01-07--14:42:27.767 - UiUserPreferences - Loading user preference 'soundEffects' value: 
2024-01-07--14:42:27.777 - UiUserPreferences - Storing user preference 'lastProgramVersion' value: 2.11.6
2024-01-07--14:42:27.783 - UiUserPreferences - Storing user preference 'lastStart' value: 2024-01-07T14:42:27.783051300
2024-01-07--14:42:31.301 - unknown - NullPointerException
2024-01-07--14:42:31.303 - IntervalMusicCompositorUI - java.lang.NullPointerException
                at java.base/java.io.File.<init>(File.java:278)
                at intervalmusiccompositor.ui.fx/ch.retorte.intervalmusiccompositor.ui.mainscreen.MainScreenController.openDirectoryChooser(MainScreenController.java:637)
                at intervalmusiccompositor.ui.fx/ch.retorte.intervalmusiccompositor.ui.mainscreen.MainScreenController.lambda$initializeOutputDirectory$28(MainScreenController.java:466)
                at javafx.base@21.0.1/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
                at javafx.base@21.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
                at javafx.base@21.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
                at javafx.base@21.0.1/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
                at javafx.base@21.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
                at javafx.base@21.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
                at javafx.base@21.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
                at javafx.base@21.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
                at javafx.base@21.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
                at javafx.base@21.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
                at javafx.base@21.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
                at javafx.base@21.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
                at javafx.base@21.0.1/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
                at javafx.base@21.0.1/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
                at javafx.base@21.0.1/javafx.event.Event.fireEvent(Event.java:198)
                at javafx.graphics@21.0.1/javafx.scene.Node.fireEvent(Node.java:8875)
                at javafx.controls@21.0.1/javafx.scene.control.Button.fire(Button.java:203)
                at javafx.controls@21.0.1/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:207)
                at javafx.controls@21.0.1/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
                at javafx.base@21.0.1/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
                at javafx.base@21.0.1/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
                at javafx.base@21.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
                at javafx.base@21.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
                at javafx.base@21.0.1/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
                at javafx.base@21.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
                at javafx.base@21.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
                at javafx.base@21.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
                at javafx.base@21.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
                at javafx.base@21.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
                at javafx.base@21.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
                at javafx.base@21.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
                at javafx.base@21.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
                at javafx.base@21.0.1/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
                at javafx.base@21.0.1/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
                at javafx.base@21.0.1/javafx.event.Event.fireEvent(Event.java:198)
                at javafx.graphics@21.0.1/javafx.scene.Scene$MouseHandler.process(Scene.java:3984)
                at javafx.graphics@21.0.1/javafx.scene.Scene.processMouseEvent(Scene.java:1890)
                at javafx.graphics@21.0.1/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2708)
                at javafx.graphics@21.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
                at javafx.graphics@21.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
                at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
                at javafx.graphics@21.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
                at javafx.graphics@21.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
                at javafx.graphics@21.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
                at javafx.graphics@21.0.1/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
                at javafx.graphics@21.0.1/com.sun.glass.ui.View.notifyMouse(View.java:937)
                at javafx.graphics@21.0.1/com.sun.glass.ui.win.WinApplication._runLoop(NativeMethod)
                at javafx.graphics@21.0.1/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
                at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by nwaldispuehl** [comment]
The issue is also present in previous versions like `v2.11.4`.
